// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9dGglIbQNS5Ofopy4MoGf9K3IQax_ZY',
    appId: '1:207361856408:web:2de83391f33c24267fd1ed',
    messagingSenderId: '207361856408',
    projectId: 'mad-final-dcfa6',
    authDomain: 'mad-final-dcfa6.firebaseapp.com',
    databaseURL: 'https://mad-final-dcfa6-default-rtdb.firebaseio.com',
    storageBucket: 'mad-final-dcfa6.firebasestorage.app',
    measurementId: 'G-10Q4HGSDTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CuabrcHqrlj9wlIu0geISFY6YkIvgYU',
    appId: '1:207361856408:android:f95a19f1fa1c2cd47fd1ed',
    messagingSenderId: '207361856408',
    projectId: 'mad-final-dcfa6',
    databaseURL: 'https://mad-final-dcfa6-default-rtdb.firebaseio.com',
    storageBucket: 'mad-final-dcfa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChRqZATv3MgdA-uSLIAEQ2yod8nfM3UAs',
    appId: '1:207361856408:ios:8c6091d98337c5637fd1ed',
    messagingSenderId: '207361856408',
    projectId: 'mad-final-dcfa6',
    databaseURL: 'https://mad-final-dcfa6-default-rtdb.firebaseio.com',
    storageBucket: 'mad-final-dcfa6.firebasestorage.app',
    iosBundleId: 'com.example.wishlistwonders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChRqZATv3MgdA-uSLIAEQ2yod8nfM3UAs',
    appId: '1:207361856408:ios:8c6091d98337c5637fd1ed',
    messagingSenderId: '207361856408',
    projectId: 'mad-final-dcfa6',
    databaseURL: 'https://mad-final-dcfa6-default-rtdb.firebaseio.com',
    storageBucket: 'mad-final-dcfa6.firebasestorage.app',
    iosBundleId: 'com.example.wishlistwonders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9dGglIbQNS5Ofopy4MoGf9K3IQax_ZY',
    appId: '1:207361856408:web:4fcb9d3ca409b4dd7fd1ed',
    messagingSenderId: '207361856408',
    projectId: 'mad-final-dcfa6',
    authDomain: 'mad-final-dcfa6.firebaseapp.com',
    databaseURL: 'https://mad-final-dcfa6-default-rtdb.firebaseio.com',
    storageBucket: 'mad-final-dcfa6.firebasestorage.app',
    measurementId: 'G-FKZPJKF1NX',
  );
}
